# Defines supported pre-commit hooks for this project.

- id: run-ejsonkms-encrypt
  name: run-ejsonkms-encrypt
  description: Run ejsonkms encrypt on all ejson, eyaml, and etoml files in your repository.
  entry: ejsonkms encrypt
  language: rust
  types: [file]
  files: '\.(ejson|eyaml|eyml|etoml)$'
